### ISSUE TITLE
socket timed out

### ISSUE THREAD

**Issue by openHBP** [acdh-oeaw/acdh-django-zotero#1]
* acdh-django-zotero version: 0.1.3
* Django version: 2.2.6
* Python version: 3.6.7
* Operating System: LINUX Ubuntu 18.04.3 LTS

### Description

Everything works fine in admin BUT every 3 to 5 minutes I always get the same error message in my terminal.
It seems it has to do with the 'client_address' of socketserver.ThreadingMixIn.process_request_thread(self, request, client_address)

### Console Output every 5 minutes

```
Exception happened during processing of request from ('127.0.0.1', 53344)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/pat/.local/share/virtualenvs/ctrab-jDmSEPw-/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/pat/.local/share/virtualenvs/ctrab-jDmSEPw-/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by csae8092** [comment]
I know this error as it occurs in several other projects of mine but I frankly have no idea what causes this error ...

**Comment by openHBP** [comment]
Ok, thanks for your quick answer.
